### ISSUE TITLE
Lots of warnings

### ISSUE THREAD

**Issue by ojwb** [FabriceColin/pinot#13]
I'm seeing a lot of warnings building on current Debian unstable (x86-64).

Mostly use of deprecated APIs and autotools macros, but a few are thanks to new compiler warnings:

```
autoreconf: warning: autoconf input should be named 'configure.ac', not 'configure.in'
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
```
```
configure.in:8: warning: The macro `AC_ISC_POSIX' is obsolete.
configure.in:8: You should run autoupdate.
./lib/autoconf/specific.m4:550: AC_ISC_POSIX is expanded from...
configure.in:8: the top level
configure.in:10: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.in:10: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.in:10: the top level
configure.in:14: warning: The macro `AM_PROG_LIBTOOL' is obsolete.
configure.in:14: You should run autoupdate.
aclocal.m4:610: AM_PROG_LIBTOOL is expanded from...
configure.in:14: the top level
configure.in:29: warning: The macro `GLIB_GNU_GETTEXT' is obsolete.
configure.in:29: You should run autoupdate.
aclocal.m4:388: GLIB_GNU_GETTEXT is expanded from...
aclocal.m4:488: AM_GLIB_GNU_GETTEXT is expanded from...
configure.in:29: the top level
configure.in:29: warning: The macro `AC_TRY_LINK' is obsolete.
configure.in:29: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
aclocal.m4:73: GLIB_LC_MESSAGES is expanded from...
aclocal.m4:388: GLIB_GNU_GETTEXT is expanded from...
aclocal.m4:488: AM_GLIB_GNU_GETTEXT is expanded from...
configure.in:29: the top level
configure.in:29: warning: The macro `AC_TRY_LINK' is obsolete.
configure.in:29: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/headers.m4:89: _AC_CHECK_HEADER_COMPILE is expanded from...
./lib/autoconf/headers.m4:56: AC_CHECK_HEADER is expanded from...
aclocal.m4:172: GLIB_WITH_NLS is expanded from...
aclocal.m4:388: GLIB_GNU_GETTEXT is expanded from...
aclocal.m4:488: AM_GLIB_GNU_GETTEXT is expanded from...
configure.in:29: the top level
configure.in:29: warning: The macro `AC_TRY_LINK' is obsolete.
configure.in:29: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/headers.m4:89: _AC_CHECK_HEADER_COMPILE is expanded from...
./lib/autoconf/headers.m4:56: AC_CHECK_HEADER is expanded from...
aclocal.m4:172: GLIB_WITH_NLS is expanded from...
aclocal.m4:388: GLIB_GNU_GETTEXT is expanded from...
aclocal.m4:488: AM_GLIB_GNU_GETTEXT is expanded from...
configure.in:29: the top level
configure.in:29: warning: The macro `AC_OUTPUT_COMMANDS' is obsolete.
configure.in:29: You should run autoupdate.
./lib/autoconf/status.m4:1025: AC_OUTPUT_COMMANDS is expanded from...
aclocal.m4:172: GLIB_WITH_NLS is expanded from...
aclocal.m4:388: GLIB_GNU_GETTEXT is expanded from...
aclocal.m4:488: AM_GLIB_GNU_GETTEXT is expanded from...
configure.in:29: the top level
configure.in:66: warning: The macro `AC_LANG_CPLUSPLUS' is obsolete.
configure.in:66: You should run autoupdate.
./lib/autoconf/c.m4:262: AC_LANG_CPLUSPLUS is expanded from...
configure.in:66: the top level
configure.in:300: warning: The macro `AC_TRY_LINK' is obsolete.
configure.in:300: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
configure.in:300: the top level
configure.in:429: warning: AC_OUTPUT should be used without arguments.
configure.in:429: You should run autoupdate.
```

`msgfmt` warnings:

```
es.po:7: warning: header field 'Language' still has the initial default value
fr.po:7: warning: header field 'Language' still has the initial default value
pt_BR.po:6: warning: header field 'Language' still has the initial default value
zh_TW.po:7: warning: header field 'Language' still has the initial default value
```

```
Memory.cpp: In static member function 'static int Memory::getUsage()':
Memory.cpp:86:40: warning: 'mallinfo mallinfo()' is deprecated [-Wdeprecated-declarations]
   86 |         struct mallinfo info = mallinfo();
      |                                ~~~~~~~~^~
In file included from Memory.cpp:21:
/usr/include/malloc.h:114:24: note: declared here
  114 | extern struct mallinfo mallinfo (void) __THROW __MALLOC_DEPRECATED;
      |                        ^~~~~~~~
```

```
../Tokenize/filters/GMimeMboxFilter.cc: In member function 'virtual bool Dijon::GMimeMboxFilter::skip_to_document(const std::string&)':
../Tokenize/filters/GMimeMboxFilter.cc:304:35: warning: format '%lld' expects argument of type 'long long int*', but argument 3 has type 'off_t*' {aka 'long int*'} [-Wformat=]
  304 |         if (sscanf(ipath.c_str(), "o=" GMIME_OFFSET_MODIFIER "&l=[", &m_messageStart) != 1)
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~
      |                                                                      |
      |                                                                      off_t* {aka long int*}
In file included from ../Tokenize/filters/GMimeMboxFilter.cc:37:
../Tokenize/filters/GMimeMboxFilter.h:38:35: note: format string is defined here
   38 | #define GMIME_OFFSET_MODIFIER "%lld"
      |                                ~~~^
      |                                   |
      |                                   long long int*
      |                                %ld
```

```
../Tokenize/filters/ArchiveFilter.cc: In member function 'void Dijon::ArchiveFilter::initialize()':
../Tokenize/filters/ArchiveFilter.cc:259:63: warning: 'int archive_read_support_compression_bzip2(archive*)' is deprecated [-Wdeprecated-declarations]
  259 |                         archive_read_support_compression_bzip2(m_pHandle);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
In file included from ../Tokenize/filters/ArchiveFilter.h:22,
                 from ../Tokenize/filters/ArchiveFilter.cc:32:
/usr/include/archive.h:397:15: note: declared here
  397 | __LA_DECL int archive_read_support_compression_bzip2(struct archive *)
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Tokenize/filters/ArchiveFilter.cc:265:62: warning: 'int archive_read_support_compression_gzip(archive*)' is deprecated [-Wdeprecated-declarations]
  265 |                         archive_read_support_compression_gzip(m_pHandle);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/usr/include/archive.h:401:15: note: declared here
  401 | __LA_DECL int archive_read_support_compression_gzip(struct archive *)
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Tokenize/filters/ArchiveFilter.cc:281:66: warning: 'int archive_read_support_compression_compress(archive*)' is deprecated [-Wdeprecated-declarations]
  281 |                         archive_read_support_compression_compress(m_pHandle);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/usr/include/archive.h:399:15: note: declared here
  399 | __LA_DECL int archive_read_support_compression_compress(struct archive *)
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../Tokenize/filters/ArchiveFilter.cc: In member function 'virtual void Dijon::ArchiveFilter::rewind()':
../Tokenize/filters/ArchiveFilter.cc:425:36: warning: 'int archive_read_finish(archive*)' is deprecated [-Wdeprecated-declarations]
  425 |                 archive_read_finish(m_pHandle);
      |                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/usr/include/archive.h:726:26: note: declared here
  726 | __LA_DECL int            archive_read_finish(struct archive *) __LA_DEPRECATED;
      |                          ^~~~~~~~~~~~~~~~~~~
```

```
WorkerThread.cpp: In member function 'virtual void MonitorThread::stop()':
WorkerThread.cpp:638:22: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)' declared with attribute 'warn_unused_result' [-Wunused-result]
  638 |                 write(m_ctrlWritePipe, "X", 1);
      |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```

```
In file included from /usr/include/libxml2/libxml/parser.h:13,
                 from PinotSettings.cpp:39:
PinotSettings.cpp: In constructor 'PinotSettings::PinotSettings()':
/usr/include/libxml2/libxml/xmlversion.h:500:44: warning: 'int* __xmlParserDebugEntities()' is deprecated [-Wdeprecated-declarations]
  500 |   #define XML_GLOBAL_MACRO(name) (*__##name())
      |                                    ~~~~~~~~^~
/usr/include/libxml2/libxml/parser.h:901:34: note: in expansion of macro 'XML_GLOBAL_MACRO'
  901 |   #define xmlParserDebugEntities XML_GLOBAL_MACRO(xmlParserDebugEntities)
      |                                  ^~~~~~~~~~~~~~~~
PinotSettings.cpp:127:9: note: in expansion of macro 'xmlParserDebugEntities'
  127 |         xmlParserDebugEntities = 0;
      |         ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by FabriceColin** [comment]
Thanks. I'll take a closer look.

**Comment by FabriceColin** [comment]
I have pushed potential fixes for the bottom 6 issues to master. Would you be able to take a look? I'll try and address the top one soon.

**Comment by ojwb** [comment]
Hmm, I can't even get it to build from git.

`./autogen.sh` complains about `po/Makefile.in.in` existing (which it does it git and appears to have since the code was exported from Google Code):

```
gettextize: *** po/Makefile.in.in exists: use option -f if you really want to delete it.
gettextize: *** Stop.
```

However the script doesn't stop (perhaps it should have `set -e` at the top?) and then it later complains:

```
Makefile.am: error: required file './ChangeLog' not found
```

Again it keeps going, runs `configure` and that fails with:

```
configure: creating ./config.status
config.status: creating pinot.spec
config.status: creating Core/com.github.fabricecolin.Pinot.service
config.status: error: cannot find input file: 'Makefile.in'
```

I tried looking for instructions in case there was something else I needed to do and noticed there's a "2. Building Pinot" in the `README` file's list of sections, which doesn't actually exist below (but there is another section numbered 2 which does exist):

```
1. What is Pinot
2. Building Pinot
2. Available engines
```

Section "15. Compiling" also seemed promising didn't seem to help with building from git.  Nothing in the tree seems to even mention `./autogen.sh`.

**Comment by FabriceColin** [comment]
Added instructions under "15. Compiling", and looking into removing the remaining warnings.

**Comment by ojwb** [comment]
Thanks, that's improved things.

I do still get:

```
gettextize: *** po/Makefile.in.in exists: use option -f if you really want to delete it.
gettextize: *** Stop.
```

However things seem to work well enough that the code configures and builds.

I get some warnings which are due to uses of `std::auto_ptr<>` in the libxml++ headers so not pinot's fault, e.g.:

```
In file included from /usr/include/libxml++-2.6/libxml++/libxml++.h:55,
                 from OpenSearchParser.cpp:25:
/usr/include/libxml++-2.6/libxml++/parsers/saxparser.h:247:8: warning: 'template<class> class std::auto_ptr' is deprecated: use 'std::unique_ptr' instead [-Wdeprecated-declarations]
  247 |   std::auto_ptr<_xmlSAXHandler> sax_handler_;
      |        ^~~~~~~~
```

However, I think this one is pinot using something deprecated:

```
In file included from /usr/include/libxml2/libxml/parser.h:13,
                 from PinotSettings.cpp:39:
PinotSettings.cpp: In constructor 'PinotSettings::PinotSettings()':
/usr/include/libxml2/libxml/xmlversion.h:500:44: warning: 'int* __xmlParserDebugEntities()' is deprecated [-Wdeprecated-declarations]
  500 |   #define XML_GLOBAL_MACRO(name) (*__##name())
      |                                    ~~~~~~~~^~
/usr/include/libxml2/libxml/parser.h:901:34: note: in expansion of macro 'XML_GLOBAL_MACRO'
  901 |   #define xmlParserDebugEntities XML_GLOBAL_MACRO(xmlParserDebugEntities)
      |                                  ^~~~~~~~~~~~~~~~
PinotSettings.cpp:128:9: note: in expansion of macro 'xmlParserDebugEntities'
  128 |         xmlParserDebugEntities = 0;
      |         ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/libxml2/libxml/xmlversion.h:499:27: note: declared here
  499 |     attrs XMLPUBFUN type *__##name(void);
      |                           ^~
/usr/include/libxml2/libxml/parser.h:885:16: note: in expansion of macro 'XML_DECLARE_GLOBAL'
  885 | #define XML_OP XML_DECLARE_GLOBAL
      |                ^~~~~~~~~~~~~~~~~~
/usr/include/libxml2/libxml/parser.h:860:3: note: in expansion of macro 'XML_OP'
  860 |   XML_OP(xmlParserDebugEntities, int, XML_DEPRECATED) \
      |   ^~~~~~
/usr/include/libxml2/libxml/parser.h:881:3: note: in expansion of macro 'XML_GLOBALS_PARSER_CORE'
  881 |   XML_GLOBALS_PARSER_CORE \
      |   ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/libxml2/libxml/parser.h:886:1: note: in expansion of macro 'XML_GLOBALS_PARSER'
  886 | XML_GLOBALS_PARSER
      | ^~~~~~~~~~~~~~~~~~
```

**Comment by ojwb** [comment]
For me `LIBXML_VERSION` is `21207` so I wonder if your new check in `Core/PinotSettings.cpp` is using the wrong threshold:

```
#if LIBXML_VERSION < 21208
```

Looking at libxml2's NEWS, I think this was probably deprecated in 2.12.0:

> - parser: Deprecate global parser options

**Comment by FabriceColin** [comment]
I was going to ask you what version Debian has. I'll go for 2.12.0.

**Comment by FabriceColin** [comment]
Also pushed a move to libxml++ 3.2.

**Comment by FabriceColin** [comment]
I have tried a few things to get rid of the remaining build warnings generated at the configure step but haven't found a satisfactory solution yet. I am going to release 1.22 as is and revisit this at some point. These warnings don't seem to be show-stoppers.
